name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências do requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar pasta de resultados
        run: mkdir -p results

      - name: Rodar testes Robot Framework
        run: |
          robot --output results/output.xml \
                --log results/log.html \
                --report results/report.html \
                login_tests/

      - name: Publicar artefatos (relatórios)
        uses: actions/upload-artifact@v3
        with:
          name: robot-report
          path: results/
